### ISSUE TITLE
error: ‘n’ not specified in enclosing ‘parallel’

### ISSUE THREAD

**Issue by jschueller** [SGpp/SGpp#224]
I got compilation error due to the openmp syntax used in base/tools/sle/solver/Gmmpp.cpp,Armadillo.cpp,Eigen.cpp with gcc 9.x
look for lines containing "#pragma omp parallel if (system.isCloneable()) shared(system, A, nnz, rowsDone)"
a possible fix is to add 'n' to the list of shared variables but I'm no openmp expert

**Comment by MichaelReh** [comment]
There is more information on this at ['Porting to GCC 9'](https://gcc.gnu.org/gcc-9/porting_to.html) under 'OpenMP data sharing'.
They recommend to simply drop 'deault(none)', which works fine for me with gcc 9.2.1

**Comment by jschueller** [comment]
so these should be fixed:
https://github.com/SGpp/SGpp/search?l=C%2B%2B&q=%22default%28none%29%22

**Comment by MichaelReh** [comment]
On second thought keeping default(none) and adding n to shared is better in terms of code understandability and maintainability. However, when doing so I still get errors
‘_ZTIN4sgpp4base12CloneableSLEE’ not specified in enclosing ‘parallel'
‘_ZTIN4sgpp4base3SLEE’ not specified in enclosing ‘parallel’
both pointing to the line
dynamic_cast<CloneableSLE&>(system).clone(clonedSLE);

**Comment by valentjn** [comment]
This is related to https://github.com/SGpp/SGpp/issues/127.
